# Numpay and if...else statment

In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [3]:
x[0,0]

1

In [4]:
x[0,1]

2

In [5]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
x[0]

array([1, 2, 3])

In [7]:
y = np.arange(10)
print(y)
y[2]

[0 1 2 3 4 5 6 7 8 9]


2

In [8]:
y[-2]

8

In [9]:
y[2:5]

array([2, 3, 4])

In [10]:
y[:-7]

array([0, 1, 2])

In [11]:
y[1:7:2]

array([1, 3, 5])

In [12]:
for i in range(3):
    print(i)

0
1
2


In [15]:
z = int(input("Please enter an integer: "))
if z < 0:
    z = 0
    print('Negative changed to zero')
elif z == 0:
    print('zero')
elif z == 1:
    print('Single')
else:
    print('More')
    

Please enter an integer: 9
More
