# Revision

In [2]:
import numpy as np
x = np.array([[1,2,4],[4,5,6]])
x[1,1]

5

In [3]:
x[0,0]

1

In [4]:
y = np.arange(12)
y[1]+y[-1]

12

In [5]:
for i in range(3):
    print(i)
    

0
1
2


In [6]:
print(x)

[[1 2 4]
 [4 5 6]]


In [7]:
x[1,1] - x[0,0]

4

In [8]:
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [10]:
y[1]

1

In [11]:
y[-1]

11